### ISSUE TITLE
[BUG] Error in validation of configuration file

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mihari#277]
### **Describe the bug**
Mihari generates error while validating a configuration file using `mihari validate config`.

### **Steps to reproduce**

- Create a valid configuration file.

- Run `mihari validate config /path/to/config.yml` from CLI.

### **Expected behavior**

Mihari should validate it.

### **Actual behavior**
example config file:
```yml
CENSYS_ID: bar
CENSYS_SECRET: foo
```
The error is as follows:
```bash
Failed to parse the input as a config!
Traceback (most recent call last):
	15: from /usr/local/bin/mihari:23:in `<main>'
	14: from /usr/local/bin/mihari:23:in `load'
	13: from /var/lib/gems/2.7.0/gems/mihari-3.0.0/exe/mihari:8:in `<top (required)>'
	12: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	11: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	10: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	 9: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	 8: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
	 7: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	 6: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	 5: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	 4: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	 3: from /var/lib/gems/2.7.0/gems/mihari-3.0.0/lib/mihari/commands/validator.rb:29:in `config'
	 2: from /var/lib/gems/2.7.0/gems/mihari-3.0.0/lib/mihari/mixins/configuration.rb:41:in `validate_config'
	 1: from /var/lib/gems/2.7.0/gems/mihari-3.0.0/lib/mihari/mixins/configuration.rb:41:in `each_key'
/var/lib/gems/2.7.0/gems/mihari-3.0.0/lib/mihari/mixins/configuration.rb:44:in `block in validate_config': CENSYS_ID is not a valid key. (ArgumentError)

```

### **System Information:**

- OS: `Ubuntu 20.04`
- Ruby version: `2.7`
- Mihari version: `3.0.0`

**Comment by r0ny123** [comment]
Thanks, can you highlight that line for others to notice?
