### ISSUE TITLE
[BUG] Mihari search fails using grape `1.6.1`

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mihari#379]
### **Describe the bug**

Mihari searches generate error while using grape `1.6.1` (released on 28th dec). The searches were working perfectly fine while using `1.6.0`. This is not really a bug with mihari. But any workaround for now?

### **Expected behavior**

Mihari should return the results.

### **Actual behavior**

This is the error:
```
/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/validations/params_scope.rb:359:in `infer_coercion': undefined method `multiple?' for Grape::Validations::Types:Module (NoMethodError)
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/validations/params_scope.rb:274:in `validates'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/validations/params_scope.rb:195:in `validate_attributes'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/dsl/parameters.rb:160:in `optional'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/lib/mihari/web/endpoints/alerts.rb:13:in `block (2 levels) in <class:Alerts>'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/validations/params_scope.rb:39:in `instance_eval'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/validations/params_scope.rb:39:in `initialize'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/dsl/validations.rb:42:in `new'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/dsl/validations.rb:42:in `params'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/lib/mihari/web/endpoints/alerts.rb:12:in `block in <class:Alerts>'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api/instance.rb:118:in `instance_eval'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api/instance.rb:118:in `block in evaluate_as_instance_with_configuration'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/util/lazy_block.rb:11:in `evaluate_from'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api/instance.rb:125:in `evaluate_as_instance_with_configuration'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api/instance.rb:107:in `block in nest'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api/instance.rb:107:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api/instance.rb:107:in `nest'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/dsl/routing.rb:173:in `block in namespace'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/dsl/settings.rb:162:in `within_namespace'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/dsl/routing.rb:170:in `namespace'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api.rb:160:in `replay_step_on'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api.rb:151:in `block in add_setup'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api.rb:150:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api.rb:150:in `add_setup'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/grape-1.6.1/lib/grape/api.rb:55:in `block (2 levels) in override_all_methods!'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/lib/mihari/web/endpoints/alerts.rb:6:in `<class:Alerts>'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/lib/mihari/web/endpoints/alerts.rb:5:in `<module:Endpoints>'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/lib/mihari/web/endpoints/alerts.rb:4:in `<module:Mihari>'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/lib/mihari/web/endpoints/alerts.rb:3:in `<top (required)>'
	from <internal:/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/lib/mihari/web/api.rb:20:in `<top (required)>'
	from <internal:/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/lib/mihari/web/app.rb:14:in `<top (required)>'
	from <internal:/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/lib/mihari.rb:181:in `<top (required)>'
	from <internal:/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/mihari-3.9.1/exe/mihari:6:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/bin/mihari:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/bin/mihari:25:in `<main>'
Error: Process completed with exit code 1.
```

### **Additional context**

Others may have facing this similar issue https://github.com/ruby-grape/grape/issues/2214

**Comment by ninoseki** [comment]
https://github.com/ruby-grape/grape/pull/2219
