### ISSUE TITLE
[BUG] Censys `KeyError`

### ISSUE THREAD

**Issue by ssnkhan** [ninoseki/mihari#600]
### **Describe the bug**

Censys is returning a `A KeyError occurred in the background` error. There do not appear to be any status issues with Censys API at the moment.

```
A KeyError occured in background
Exception
key not found: "next"
Hostname
[REDACTED]
Backtrace
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/censys.rb:55:in `fetch'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/censys.rb:55:in `from_dynamic!'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/censys.rb:73:in `from_dynamic!'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/censys.rb:88:in `from_dynamic!'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/censys.rb:32:in `block in search'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/censys.rb:30:in `loop'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/censys.rb:30:in `search'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/censys.rb:16:in `artifacts'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/base.rb:88:in `normalized_artifacts'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/base.rb:103:in `unique_artifacts'
```

and

```
A KeyError occured in background
Exception
key not found: "prev"
Hostname
[REDACTED]
Backtrace
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/censys.rb:56:in `fetch'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/censys.rb:56:in `from_dynamic!'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/censys.rb:73:in `from_dynamic!'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/censys.rb:88:in `from_dynamic!'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/censys.rb:32:in `block in search'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/censys.rb:30:in `loop'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/censys.rb:30:in `search'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/censys.rb:16:in `artifacts'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/base.rb:88:in `normalized_artifacts'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/base.rb:103:in `unique_artifacts'
```

### **Steps to reproduce**

- Run Censys query.
- See error in output

### **Expected behavior**

Query should return and add new IOCs.

### **Actual behavior**

Returns errors as detailed above.

### **Screenshots**

N/A

### **System Information:**

- OS: Ubuntu
- Ruby version: `ruby 2.7.0p0`
- Mihari version: `3.12.0` manually patched with other updates.

**Comment by ssnkhan** [comment]
I had these issues for around four days, but it has began working as normal now :)

**Comment by ninoseki** [comment]
I believe #610 and #603 fix the issue. Thank you for reporting!
