### ISSUE TITLE
[BUG] Issue with Censys rules

### ISSUE THREAD

**Issue by gr00T0x** [ninoseki/mihari#683]
### **Describe the bug**

When I run rules that query Censys I get a 403 returned a majority of the time. I have checked my API usage and this is low so not sure what is effecting it.
### **Steps to reproduce**

Run a rule with censys and see the error output.

### **Expected behavior**

I run a rule and it returns the expect output in Mihari.

### **Actual behavior**

The following error is returned:

2023-08-14 06:16:25.923116 E [1:6800 error_notification.rb:12] Mihari -- Exception: Mihari::StatusCodeError: Unsuccessful response code returned: 403
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/http.rb:97:in `block in request'
/usr/local/lib/ruby/3.2.0/net/http.rb:1238:in `start'
/usr/local/lib/ruby/3.2.0/net/http.rb:687:in `start'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/http.rb:94:in `request'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/http.rb:30:in `get'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/http.rb:64:in `get'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/clients/base.rb:39:in `get'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/clients/censys.rb:37:in `search'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/censys.rb:34:in `block in artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/censys.rb:33:in `loop'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/censys.rb:33:in `artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/base.rb:59:in `block in normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/mixins/retriable.rb:28:in `retry_on_error'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/base.rb:58:in `normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:62:in `each'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:62:in `flat_map'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:62:in `artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:75:in `normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:91:in `unique_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:102:in `enriched_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:132:in `run'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/commands/search.rb:49:in `block in run'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/mixins/error_notification.rb:10:in `with_error_notification'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/commands/search.rb:48:in `run'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/commands/search.rb:89:in `block in search'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/database.rb:170:in `with_db_connection'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/commands/search.rb:71:in `search'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/mihari-5.3.2/exe/mihari:8:in `<top (required)>'
/usr/local/bundle/bin/mihari:25:in `load'
/usr/local/bundle/bin/mihari:25:in `<main>'
### **Screenshots**

Add screenshots to help explain your problem.

### **System Information:**
OS: Ubuntu 20
Ruby version: (ruby:3.2.2-alpine3.18)
Mihari version: 5.3.2

### **Additional context**

I am running Mihari in Docker

**Comment by gr00T0x** [comment]
I have run the Censys queries, querying the Censys API directly with curl and have not had any errors.

**Comment by gr00T0x** [comment]
Ignore this, apologies. API keys had changed
